name: Build Hello Keycloak Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: node --version
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Upload Artifact
      if: github.ref_type != 'tag'
      uses: actions/upload-artifact@v4
      with:
        name: hello_keycloak
        path: ./dist
    - name: Build archives
      if: github.ref_type == 'tag'
      run: tar -C ./dist  -vczf hello_keycloak_${{ github.ref_name }}.tar.gz .
    - name: Create Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: hello_keycloak_${{ github.ref_name }}.tar.gz
